#!/usr/bin/env python3
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///
"""Generate Zola content from the YAML data files.

data/ is the source of truth. Everything this writes is disposable and is
recreated from scratch on every run:

    content/authors/            one page per data/authors.yml entry
    config.toml project_files   the data/projects/*.yml file list

Run it before `zola build` — the Makefile does. Nothing here reads the
generated output back, so `make clean && make build` is always a no-op diff.
"""

import glob
import os
import re
import shutil
import sys

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))

DATA = os.path.join(ROOT, "data")
AUTHORS_YML = os.path.join(DATA, "authors.yml")
FEATURED_YML = os.path.join(DATA, "featured.yml")
PROJECTS_DIR = os.path.join(DATA, "projects")

AUTHORS_DIR = os.path.join(ROOT, "content", "authors")
CONFIG = os.path.join(ROOT, "config.toml")
STATIC = os.path.join(ROOT, "static")

# build.py rewrites everything between these two lines in config.toml.
BEGIN = "# BEGIN generated by build.py — do not edit."
END = "# END generated."

BANNER = "# Generated by build.py from data/authors.yml. Do not edit."

warnings = []


def warn(msg):
    warnings.append(msg)


def die(msg):
    print(f"build.py: error: {msg}", file=sys.stderr)
    sys.exit(1)


def load(path):
    with open(path) as f:
        return yaml.safe_load(f) or []


def toml_str(s):
    """Quote a string for TOML. The values here are names and URLs, but a
    stray quote in a display name should not produce a broken config."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def owners():
    """Owner slugs, one per data/projects/<owner>.yml, sorted."""
    files = sorted(glob.glob(os.path.join(PROJECTS_DIR, "*.yml")))
    return [os.path.splitext(os.path.basename(f))[0] for f in files]


def read_projects():
    """Every project row, tagged with the file it came from."""
    rows = []
    for path in [FEATURED_YML] + [
        os.path.join(PROJECTS_DIR, o + ".yml") for o in owners()
    ]:
        src = os.path.relpath(path, ROOT)
        entries = load(path)
        if not isinstance(entries, list):
            die(f"{src}: expected a list of projects")
        for p in entries:
            rows.append((src, p))
    return rows


def read_authors():
    """Author entries keyed by handle."""
    authors = {}
    for a in load(AUTHORS_YML):
        gh = (a.get("github") or "").strip()
        if not gh:
            die(f"data/authors.yml: entry with no github handle: {a!r}")
        if gh != gh.lower():
            die(f"data/authors.yml: handle must be lowercase: {gh}")
        if gh in authors:
            die(f"data/authors.yml: duplicate handle: {gh}")
        authors[gh] = a
    return authors


def check(rows, authors):
    """Cross-file invariants that Zola cannot express."""
    seen_uri = {}
    used = set()

    for src, p in rows:
        name = p.get("name") or "<unnamed>"

        uri = (p.get("github_uri") or "").strip()
        if not uri:
            warn(f"{src}: {name}: no github_uri")
        elif uri in seen_uri:
            # featured.yml and the owner files partition the set of projects;
            # a repo in both would render twice.
            die(f"{uri} is listed twice: {seen_uri[uri]} and {src}")
        else:
            seen_uri[uri] = src

        gh = (p.get("author_github") or "").strip()
        if gh:
            if gh not in authors:
                die(
                    f"{src}: {name}: author_github '{gh}' has no entry in "
                    f"data/authors.yml"
                )
            used.add(gh)

        for field in ("image", "logo"):
            rel = (p.get(field) or "").strip()
            if rel and not os.path.exists(os.path.join(STATIC, rel)):
                warn(f"{src}: {name}: {field} not found: static/{rel}")

    for gh in sorted(set(authors) - used):
        warn(f"data/authors.yml: {gh} has no projects; the page will be empty")

    for gh in sorted(used):
        rel = (authors[gh].get("avatar") or "").strip()
        if rel and not os.path.exists(os.path.join(STATIC, rel)):
            warn(f"data/authors.yml: {gh}: avatar not found: static/{rel}")


def write_authors(authors):
    """One page per author, plus the section index."""
    if os.path.isdir(AUTHORS_DIR):
        shutil.rmtree(AUTHORS_DIR)
    os.makedirs(AUTHORS_DIR)

    with open(os.path.join(AUTHORS_DIR, "_index.md"), "w") as f:
        f.write(
            f"+++\n"
            f"{BANNER}\n"
            f'title = "Authors"\n'
            f"render = false\n"
            f'sort_by = "title"\n'
            f"+++\n"
        )

    for gh, a in sorted(authors.items()):
        lines = [
            "+++",
            BANNER,
            f"title = {toml_str(a.get('name') or gh)}",
            'template = "author.html"',
            "",
            "[extra]",
            f"github = {toml_str(gh)}",
        ]
        for field in ("homepage", "email", "avatar"):
            v = (a.get(field) or "").strip()
            if v:
                lines.append(f"{field} = {toml_str(v)}")
        lines.append("+++")

        bio = (a.get("bio") or "").strip()
        if bio:
            lines += ["", bio]

        with open(os.path.join(AUTHORS_DIR, gh + ".md"), "w") as f:
            f.write("\n".join(lines) + "\n")

    return len(authors)


def write_config(names):
    """Rewrite the project_files array in place.

    Zola's load_data cannot glob a directory, so the templates loop over this
    list. Deriving it from the directory is what keeps a new owner file from
    being silently invisible to the build.
    """
    with open(CONFIG) as f:
        src = f.read()

    block = [BEGIN, "project_files = ["]
    line = " "
    for n in names:
        item = f' "{n}",'
        if len(line) + len(item) > 78:
            block.append(line)
            line = " "
        line += item
    block += [line, "]", END]
    body = "\n".join(block)

    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(src):
        die(
            f"config.toml: missing the generated block. Re-add:\n\n"
            f"{BEGIN}\n{END}"
        )

    out = pattern.sub(lambda _: body, src)
    if out != src:
        with open(CONFIG, "w") as f:
            f.write(out)
    return len(names)


def main():
    if not os.path.isdir(PROJECTS_DIR):
        die("data/projects/ not found; run build.py from the repo root")

    names = owners()
    rows = read_projects()
    authors = read_authors()

    check(rows, authors)

    n_authors = write_authors(authors)
    n_owners = write_config(names)

    for w in warnings:
        print(f"build.py: warning: {w}", file=sys.stderr)

    print(
        f"build.py: {len(rows)} projects, {n_authors} author pages, "
        f"{n_owners} owner files"
    )


if __name__ == "__main__":
    main()
