#!/usr/bin/env python3
# /// script
# requires-python = ">=3.8"
# dependencies = ["pyyaml"]
# ///

import argparse
import glob
import json
import os
import re
import shutil
import sys
import urllib.error
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))

DATA = os.path.join(ROOT, "data")
AUTHORS_YML = os.path.join(DATA, "authors.yml")
FEATURED_YML = os.path.join(DATA, "featured.yml")
PROJECTS_DIR = os.path.join(DATA, "projects")

AUTHORS_DIR = os.path.join(ROOT, "content", "authors")
CONFIG = os.path.join(ROOT, "config.toml")
STATIC = os.path.join(ROOT, "static")

BEGIN = "# BEGIN generated by build.py — do not edit."
END = "# END generated."

BANNER = "# Generated by build.py from data/authors.yml. Do not edit."

API = "https://api.github.com/repos/"

# Field order every project entry is written back in. Documented in
# data/featured.yml.
FIELDS = [
    "name",
    "description",
    "category",
    "dogfood",
    "language",
    "license",
    "stars",
    "topics",
    "updated_at",
    "github_uri",
    "repo_url",
    "homepage_url",
    "image",
    "logo",
    "author_github",
]

GITHUB_FIELDS = {
    "name": lambda repo: repo.get("name"),
    "description": lambda repo: (repo.get("description") or "").strip(),
    "language": lambda repo: repo.get("language"),
    "license": lambda repo: spdx_of(repo),
    "stars": lambda repo: repo.get("stargazers_count"),
    "topics": lambda repo: sorted(repo.get("topics") or []),
    "updated_at": lambda repo: repo.get("pushed_at"),
    "github_uri": lambda repo: repo.get("full_name"),
    "repo_url": lambda repo: repo.get("html_url"),
    "homepage_url": lambda repo: (repo.get("homepage") or "").strip(),
}

warnings = []


def warn(msg):
    warnings.append(msg)


def die(msg):
    print(f"build.py: error: {msg}", file=sys.stderr)
    sys.exit(1)


def load(path):
    with open(path) as f:
        return yaml.safe_load(f) or []


def toml_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def owners():
    files = sorted(glob.glob(os.path.join(PROJECTS_DIR, "*.yml")))
    return [os.path.splitext(os.path.basename(f))[0] for f in files]


def project_files():
    return [FEATURED_YML] + [
        os.path.join(PROJECTS_DIR, o + ".yml") for o in owners()
    ]


def load_projects(path):
    entries = load(path)
    if not isinstance(entries, list):
        die(f"{os.path.relpath(path, ROOT)}: expected a list of projects")
    return entries


def read_projects():
    return [
        (os.path.relpath(path, ROOT), p)
        for path in project_files()
        for p in load_projects(path)
    ]


def read_authors():
    authors = {}
    for a in load(AUTHORS_YML):
        gh = (a.get("github") or "").strip()
        if not gh:
            die(f"data/authors.yml: entry with no github handle: {a!r}")
        if gh != gh.lower():
            die(f"data/authors.yml: handle must be lowercase: {gh}")
        if gh in authors:
            die(f"data/authors.yml: duplicate handle: {gh}")
        authors[gh] = a
    return authors


def check(rows, authors):
    seen_uri = {}
    used = set()

    for src, p in rows:
        name = p.get("name") or "<unnamed>"

        uri = (p.get("github_uri") or "").strip()
        if not uri:
            warn(f"{src}: {name}: no github_uri")
        elif uri in seen_uri:
            die(f"{uri} is listed twice: {seen_uri[uri]} and {src}")
        else:
            seen_uri[uri] = src

        gh = (p.get("author_github") or "").strip()
        if gh:
            if gh not in authors:
                die(
                    f"{src}: {name}: author_github '{gh}' has no entry in "
                    f"data/authors.yml"
                )
            used.add(gh)

        for field in ("image", "logo"):
            rel = (p.get(field) or "").strip()
            if rel and not os.path.exists(os.path.join(STATIC, rel)):
                warn(f"{src}: {name}: {field} not found: static/{rel}")

    for gh in sorted(set(authors) - used):
        warn(f"data/authors.yml: {gh} has no projects; the page will be empty")

    for gh in sorted(used):
        rel = (authors[gh].get("avatar") or "").strip()
        if rel and not os.path.exists(os.path.join(STATIC, rel)):
            warn(f"data/authors.yml: {gh}: avatar not found: static/{rel}")


def write_authors(authors):
    if os.path.isdir(AUTHORS_DIR):
        shutil.rmtree(AUTHORS_DIR)
    os.makedirs(AUTHORS_DIR)

    with open(os.path.join(AUTHORS_DIR, "_index.md"), "w") as f:
        f.write(
            f"+++\n"
            f"{BANNER}\n"
            f'title = "Authors"\n'
            f"render = false\n"
            f'sort_by = "title"\n'
            f"+++\n"
        )

    for gh, a in sorted(authors.items()):
        lines = [
            "+++",
            BANNER,
            f"title = {toml_str(a.get('name') or gh)}",
            'template = "author.html"',
            "",
            "[extra]",
            f"github = {toml_str(gh)}",
        ]
        for field in ("homepage", "email", "avatar"):
            v = (a.get(field) or "").strip()
            if v:
                lines.append(f"{field} = {toml_str(v)}")
        lines.append("+++")

        bio = (a.get("bio") or "").strip()
        if bio:
            lines += ["", bio]

        with open(os.path.join(AUTHORS_DIR, gh + ".md"), "w") as f:
            f.write("\n".join(lines) + "\n")

    return len(authors)


def write_config(names):
    with open(CONFIG) as f:
        src = f.read()

    block = [BEGIN, "project_files = ["]
    line = " "
    for n in names:
        item = f' "{n}",'
        if len(line) + len(item) > 78:
            block.append(line)
            line = " "
        line += item
    block += [line, "]", END]
    body = "\n".join(block)

    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(src):
        die(
            f"config.toml: missing the generated block. Re-add:\n\n"
            f"{BEGIN}\n{END}"
        )

    out = pattern.sub(lambda _: body, src)
    if out != src:
        with open(CONFIG, "w") as f:
            f.write(out)
    return len(names)


def scalar(v):
    if v is None or v == "":
        return ""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)

    s = str(v)
    try:
        plain = yaml.safe_load(s) == s
    except yaml.YAMLError:
        plain = False
    if plain:
        return s

    escaped = (
        s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    )
    return '"' + escaped + '"'


def emit(p):
    lines = []
    for i, f in enumerate(FIELDS):
        prefix = "- " if i == 0 else "  "
        if f == "topics":
            topics = p.get("topics") or []
            if not topics:
                lines.append(prefix + "topics: []")
            else:
                lines.append(prefix + "topics:")
                lines += ["    - " + scalar(t) for t in topics]
            continue
        lines.append((prefix + f + ": " + scalar(p.get(f))).rstrip())
    return "\n".join(lines)


def header_of(path):
    with open(path) as f:
        src = f.read()

    head = []
    for line in src.splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            break
        head.append(line)
    while head and not head[-1].strip():
        head.pop()
    return head


def render(header, entries):
    out = "\n".join(header) + "\n\n" if header else ""
    out += "\n\n".join(emit(p) for p in entries) + "\n" if entries else "[]\n"
    return out


def write_projects(path, header, entries):
    out = render(header, entries)

    with open(path) as f:
        if f.read() == out:
            return False

    with open(path, "w") as f:
        f.write(out)
    return True


def gh_get(uri, token):
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "4thcrosslabs-build.py",
    }
    if token:
        headers["Authorization"] = "Bearer " + token

    req = urllib.request.Request(API + uri, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        if e.code in (404, 451):
            return None
        raise


def spdx_of(repo):
    v = ((repo.get("license") or {}).get("spdx_id") or "").strip()
    return "" if v == "NOASSERTION" else v


def apply_repo(p, repo):
    """Overwrite p with everything GitHub reports. Returns what changed."""
    before = dict(p)
    for field, value_of in GITHUB_FIELDS.items():
        value = value_of(repo)
        if value is not None and value != "":
            p[field] = value
    return [f for f in FIELDS if before.get(f) != p.get(f)]


def sync_github():
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not token:
        warn("no GITHUB_TOKEN set; unauthenticated calls are capped at 60/hour")

    synced = 0
    touched = []

    for path in project_files():
        src = os.path.relpath(path, ROOT)
        entries = load_projects(path)

        for p in entries:
            name = p.get("name") or "<unnamed>"
            uri = (p.get("github_uri") or "").strip()
            if not uri:
                warn(f"{src}: {name}: no github_uri")
                continue

            try:
                repo = gh_get(uri, token)
            except (urllib.error.URLError, OSError, ValueError) as e:
                warn(f"{src}: {uri}: {e}")
                continue

            if repo is None:
                warn(f"{src}: {uri}: gone from GitHub (deleted or private)")
                continue

            synced += 1
            changed = apply_repo(p, repo)
            if changed:
                print(f"build.py: {uri}: {', '.join(changed)}")

        if write_projects(path, header_of(path), entries):
            touched.append(src)

    if synced == 0:
        die("no repositories could be fetched; check GITHUB_TOKEN and network")

    print(f"build.py: synced {synced} repos, {len(touched)} files updated")


# --- entry point -------------------------------------------------------


def build():
    names = owners()
    rows = read_projects()
    authors = read_authors()

    check(rows, authors)

    n_authors = write_authors(authors)
    n_owners = write_config(names)

    print(
        f"build.py: {len(rows)} projects, {n_authors} author pages, "
        f"{n_owners} owner files"
    )


def main():
    ap = argparse.ArgumentParser(prog="build.py")
    sub = ap.add_subparsers(dest="mode", required=True)

    sub.add_parser(
        "build", help="generate author pages and config.toml from data/"
    )

    sub.add_parser(
        "sync-github", help="refresh project metadata from the GitHub API"
    )

    args = ap.parse_args()

    if not os.path.isdir(PROJECTS_DIR):
        die("data/projects/ not found; run build.py from the repo root")

    if args.mode == "build":
        build()
    else:
        sync_github()

    for w in warnings:
        print(f"build.py: warning: {w}", file=sys.stderr)


if __name__ == "__main__":
    main()
